services:
  mongodb:
    image: mongo:7.0
    container_name: facesecure_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: facesecure_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: facesecure_frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mongodb_data:
